CREATE TABLE bank_account (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar NOT NULL UNIQUE,
    money float NOT NULL,
    emoney float NOT NULL
);

INSERT INTO bank_account (name, money, emoney) VALUES ('A', 5000, 0);